### ISSUE TITLE
ENVIRONMENTAL CONTROL - Orbital and Radiation analysis

### ISSUE THREAD

**Issue by kevvillarreal** [CougsInSpace/CougSat1-Hardware#308] opened 2018-09-06 00:24 UTC
Using an orbital simulator and or iterations, determine the max and min temperatures for our cube in orbit using our thermal shielding materials. Also determine if our beta angle is sufficient to keep our temperature in range to provide a successful mission.

**Comment by mvguerrero** [comment] 2018-09-27 00:35
Here's a quick summary of the meeting with Dr. Richards
Meeting with Dr. Richards said what we had was on track and good. Missing a few things such as the transient calculations, ( we assumed steady state). Steady state assumes our mass is close to zero. If our mass is zero as we pass the line between dark and light, the temperature change will be instant.  CANNOT ASSUME STEADY STATE. That's where the mass comes in. He said our radiation equation was right, but we need to set it equal to the (M*CP*DeltaTemp)/Time. He also said that because our layering will be very small in mass, using it will have a great effect on the radiation equations than the MCPDeltaT/Time. We have good equations, that we just need to hone with existing information. We also got input on how to test with the vacuum chamber. Summary: we are going to strap a resistor coil to one side of the satellite, we can measure the temperature of the resistor on one side, assume it's the same all around the resistor. We will measure the power consumed by the resistor, and extrapolate the energy output in watts.  Then we read the measurements from the cubesat's interior, and compare to the equation model.

These refinements must be made before the issue is closed, so we are moving the sprint

**Comment by mvguerrero** [comment] 2019-03-24 19:37
In our albeit short experience with free orbital simulation software like NASA's GMAT, we have concluded that utilizing this method of environmental simulation is not time effective for our time-frame. There's a steep learning curve to be surmounted before viable results could be had, and there's no way to know if someone who reached that level will stay with us. Overall, the risks outweigh the benefits for the team at this stage of our project.  

Since we explored this method and invested in learning enough about it to know it won't be viable, I am downgrading this issue to Intermediate. We didn't utilize the simulation software to the fullest extent, but I want to be fair to those who worked hard to discover this fact.

**Closed by mvguerrero** 2019-03-24 19:37 UTC
Labels: Hardware, Intermediate, Team-Environmental Control
